MT_CNN.py:
  shared_layers: [(64,3,1,1)]
MT_CNN_Attention.py:
  shared_layers: [(64,3,1,1)]
dataset.py:
  non_outlier: None
  val_size: None
  level: 7
  feature_transformer: 'CLR'
  softlabel: True
  data_vis: 'visualize'
  data_augumentation: None #'smoter' #None #'smoter' #'smoter' #'smoter' #'gaussian_copula'
  num_augumentation: 200
  num_epochs: 30
  batch_size: 32
  n_trials: 1
  clustering: False
  hist: False
  num_clusters: 2
  marginal_hist_train: False
  unknown_drop: True
  asv_path_linux: '/home/nomura/Agri_Chemical_NN/data/raw/DRA015491/lv6.csv' #'data/raw/riken/taxon_data/lv6.csv' # # #
  chem_path_linux:  '/home/nomura/Agri_Chemical_NN/data/raw/DRA015491/chem_data.xlsx' #'data/raw/riken/chem_data.xlsx' # # #
  asv_path_windows: 'C:\Users\asahi\Agri_Chemical_NN\data\raw\DRA015491\lv6.csv'
  chem_path_windows: 'C:\Users\asahi\Agri_Chemical_NN\data\raw\DRA015491\chem_data.xlsx'
  reg_list2: ['experimental_purpose'] #['pH_dry_soil'] #[] #['pH_dry_soil'] #[] #
  exclude_ids2: []
  combat: False
  stats_features: ['crop', 'pref', 'lati', 'long']
  sparce_drop: True
  drop_threshold: 0.05
  uncultured_drop: True
train.py:
  early_stopping: True
  patience: 20
  least_epoch: 0
  visualize: False
  epochs: 4000
  vis_step: 5
  validation: True
  lambda: 0.1
  learning_rate: [0.01]
  weights: [0.1, 0.9, 1.0, 1.0, 1.0, 1.0]
  SUM_train_lim: 10
  personal_train_lim: 1
  l2_shared: False
  lambda_l2: 1.0
  lambda_l1: 0.01
  GradNorm_alpha: 1.0
  tr_loss: False
  tracenorm_rho: 3.0
  tracenorm_lambda: 1.0
  lasso: True
  lasso_alpha: 0.0
  AdaBN: False
  FDS: 'DWMixup'
  weight_decay: 0.1
train_PSO.py: 
  visualize: False
  epochs: 300
  vis_step: 5
  validation: True
  tr_loss: False
  W: 0.5
  C1: 1.5
  C2: 1.5
  n_particles: 30
train_GP.py:
  epochs: 10000
  patience: 20
  early_stopping: True
  visualize: False
  validation: True
  least_epoch: 0
  learning_rate: [0.1]
  weights: [0.1, 0.9, 1.0, 1.0, 1.0, 1.0]
  vis_step: 5
  tr_loss: False
  AdaBN: False
train_HBM.py:
  learning_rate: 0.1
  num_iterations: 1000
train_lf.py:
  lr: 0.01
  batch_size: 126
  epochs: 200
  early_stopping: True
  patience: 10
  meta_model_type: 'Ridge'
train_FT.py:
  lr: 0.01
  batch_size: 256
  num_epochs: 600
  early_stopping: True
  patience: 10
  l1_lambda: 0.0
  tsne_plot_epoch_freq: 0
  tsne_perplexity: 30
  tsne_max_samples: 10000
  kl_anneal_epochs: 20
  kl_max_beta: 0.1
  sparse_lambda: 0.1
  sparsity_target: 0.01
train_FT_DAE.py:
  lr: 0.01
  batch_size: 256
  num_epochs: 600
  early_stopping: True
  patience: 10
  l1_lambda: 0.0
  tsne_plot_epoch_freq: 0
  tsne_perplexity: 30
  tsne_max_samples: 10000
  noise_type: 'mask' #'gaussian' #
  noise_ratio: 0.2
train_MoE.py:
  lr: 0.01
  epochs: 2000
  early_stopping: True
  patience: 10
  tr_loss: True
  load_balancing_alpha: 10
train_GP_NUTS.py:
  num_samples: 200
  warmup_steps: 300
  num_chains: 1
train_TabPFN.py:
  optune: False
  n_trials: 50
  filter_mi: False
  data_aug: False
test.py:
  loss_sum: 'WeightedSUM' #'SUM' #
  num_predictive_samples: 100
  shap_eval: True
  save_feature: False
  batch_size: 256
  Adapte: None #'Adapter' #retrain #'retrain' #'AdaBN' #'retrain' #None #'retrain' #
  reconstruction_plots: False #False #True
  shared_learn: True #True #False
  lime_eval: False #True
fold_eval.py:
  feature_selection: None
  num_selected_features: 15
  feature_selection_all: False
  start_features: 3
  selection_ratio: 0.0
  end_features: 20
  feature_selection_dir: 'result_DRA_NN'
  carr_calc: False
  marginal_hist: False
  k_fold: 5
  feature_normalize: True
  model_name: 'TabPFN'
  result_average: 'result.csv'
  result_fold: 'fold_result.csv'
  reduced_feature: 'reduced_feature'
  comp_method: 'SUM'
  selection: 'ElasticNet_ss' #'RF_importance' #'lasso'  #'lasso' #'LGB_importance' #None #'ElasticNet' #None # #None #
  num_features_to_select_lgb: 200
  augment_method: None #'gaussian' #None #'gaussian' #None #
  exclude_ids: [
    #'042_20_Sait_Eggp'
    #'042_20_Sait_Eggp','235_21_Miyz_Spin', '360_22_Miee_Soyb', '121_20_Miyz_Spin', '125_20_Miyz_Spin', #'161_21_Miyz_Spin' #☓
    
    '041_20_Sait_Carr', '043_20_Sait_Carr', '046_20_Sait_Burd', '047_20_Sait_Burd', 
    '044_20_Sait_Broc', '045_20_Sait_Broc', '061_20_Naga_Barl', '062_20_Naga_Barl', 
    '331_22_Niig_jpea', '332_22_Niig_jpea', 
    '067_20_Naga_Pump', '050_20_Sait_Stra', '048_20_Sait_Yama',  '049_20_Sait_Yama', 
    '063_20_Naga_Onio', '064_20_Naga_Onio', '065_20_Naga_Onio', '066_20_Naga_Onio',

    '042_20_Sait_Eggp', '214_21_Miyz_Edam', '273_22_Naga_Rice', '235_21_Miyz_Spin',

    # '186_21_Miyz_Spin', '133_21_Akit_Edam', '264_21_Naga_Appl', '244_21_Aomo_Appl',
    # '132_21_Akit_Edam', '240_21_Aomo_Appl', '252_21_Aomo_Appl', '250_21_Aomo_Appl', 
    # '213_21_Miyz_Edam', 

    #'239_21_Aomo_Appl', '241_21_Aomo_Appl', '347_22_Yama_Rice', '243_21_Aomo_Appl', 
    #'122_20_Miyz_Spin', #'228_21_Miyz_Edam'
    '145_21_Miyz_Spin',
    '163_21_Miyz_Spin', #'171_21_Miyz_Spin',
    '141_21_Miyz_Spin', #'146_21_Miyz_Spin',

    '161_21_Miyz_Spin',

    # '166_21_Miyz_Spin', '150_21_Miyz_Spin', 
    # '170_21_Miyz_Spin', #'156_21_Miyz_Spin', 
    # '167_21_Miyz_Spin', 
    # '327_22_Niig_Pear', 
    # '330_22_Niig_Pear',

    '137_21_Akit_Soyb', #'231_21_Miyz_Edam',
    #'167_21_Miyz_Spin', #'244_21_Aomo_Appl'
    #'261_21_Naga_Appl'

    #'239_21_Aomo_Appl'
    #'125_20_Miyz_Spin', '121_20_Miyz_Spin', 
  ]
  feature_path_linux: 'data/raw/riken/taxon_data/lv6.csv' #'/home/nomura/Agri_Chemical_NN/data/raw/DRA015491/lv6.csv' # # #
  target_path_linux:  'data/raw/riken/chem_data.xlsx' #'/home/nomura/Agri_Chemical_NN/data/raw/DRA015491/chem_data.xlsx' # # #
  feature_path_windows: 'C:\Users\asahi\Agri_Chemical_NN\data\raw\riken\taxon_data\lv6_filtered.csv' #'C:\Users\asahi\Agri_Chemical_NN\data\raw\DRA015491\lv6.csv' #
  target_path_windows: 'C:\Users\asahi\Agri_Chemical_NN\data\raw\riken\chem_filtered.xlsx' #'C:\Users\v' #'C:\Users\asahi\Agri_Chemical_NN\data\raw\DRA015491\chem_data.xlsx' #
  data_inte: False
  transformer: ['YJ', None] #[None, 'SS','SS', 'SS','SS', 'SS',] #['SS', 'SS', 'SS', 'SS', 'SS', 'SS'] ##['SS', 'SS'] #[None, None, None, None, None, None] #
  reg_loss_fanction: ['mse', 'cross'] #['mse', 'mse'] #['mse','mse','mse','mse','mse','mse'] #['Uncertainly', 'Uncertainly'] #['mse','mse', 'mse','mse', 'mse','mse']
  eval_reg: ['R', 'R2', 'MedAE', 'MAE', 'RMSLE', 'RMSE', 'MAPE']
  eval_class: ['accuracy', 'F1score']
  labels: ['crop'] #['experimental_purpose'] # #['crop'] # #['crop'] #['crop', 'pref', 'lati', 'long'] # #
  embedding: 'concat' #'Word2Vec' #'Onehot' # #"concat" #
  embedding_size: 8
  latent_dim: 64
  skip_domains: [
                'Miyazaki-Spinach', 
                'Saitama-Spinach', 
                'Saitama-Pear', 
                'Niigata-Pear', 
                'Miyazaki-Edamame', 
  ]
  add_columns: [] #['crop', 'pref']  #['crop', 'pref'] #[] #
  features_plot: True
  hyper_optimize: False
  shap_comppute: False
main.py:
  result_dir: 'result_YJ_CLR_ENss200_nfold'
  Cross_val: True
  LOGO: False
  domains: 'year' #'pref-crop'
  reg_list: [
            # ['pref'], 
            # ['crop'], 
            # ['APCP_Mar_me'],
            # ['APCP_Feb_me'],
            # ['APCP_Jan_me'],

            # ['Tmea_Apr_me'],
            # ['Tmea_May_me'],
            # ['Tmea_Jun_me'],
            # ['Tmea_Jul_me'],
            # ['Tmea_Aug_me'],

            # ['APCP_Aug_me'],
            # ['APCP_Jul_me'],
            # ['APCP_Jun_me'],
            # ['APCP_May_me'],
            # ['APCP_Apr_me'],
            # ['APCP_Mar_me'],
            # ['APCP_Feb_me'],
            # ['APCP_Jan_me'],

            #['Available.P_th'],
            #[NH4.N], 
            ['Available.P'], 
            ['pH'], 
            #['NO3.N'], 
            #['EC'], 
            # ['Humus'], 
            # ['Exchangeable.K'], 
            # ['CEC'], 
            # ['pH_dry_soil', 'available_P', 'EC_electric_conductivity', 'Total_C', 'Total_N']
            #['pH', 'Available.P'] 

            #['available_P'], ['EC_electric_conductivity'], ['Total_C'], ['Total_N'], ['pH_dry_soil']
  ]
