MT_CNN.py:
  shared_layers: [(64,3,1,1)]
MT_CNN_Attention.py:
  shared_layers: [(64,3,1,1)]
dataset_label.py:
  non_outlier: 'None'
  val_size: 0.2
  level: 7
train_label.py:
  early_stopping: False
  patience: 5
  least_epoch: 60
  loss_sum: 'Normalized'
  visualize: False
  epochs: 40
  validation: True
  lambda: 0.0
test_label.py:
  learning_rate: 0.001
fold_eval_label.py:
  k_fold: 5
  model_name: 'CNN_condSE'
  result_dir: 'result_cond'
  result_average: 'result.csv'
  result_fold: 'fold_result.csv'
  'reduced_feature': reduced_feature
  exclude_ids: [
    '041_20_Sait_Carr', '042_20_Sait_Eggp', '043_20_Sait_Carr', '044_20_Sait_Broc',
    '045_20_Sait_Broc', '046_20_Sait_Burd', '047_20_Sait_Burd', '048_20_Sait_Yama',
    '049_20_Sait_Yama', '050_20_Sait_Stra', '061_20_Naga_Barl', '062_20_Naga_Barl',
    '067_20_Naga_Pump', '331_22_Niig_jpea', '332_22_Niig_jpea'
  ]
  feature_path: 'data/raw/taxon_data/lv7.csv'
  target_path: 'data/raw/chem_data.xlsx'
main_label.py:
  reg_list: [
            ['pH']
      ]
  label_list: ['croptype']
  